"""
Django settings for bcris_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")  # .env.example ile uyumlu

DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") + ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://bcris.site',
    'https://www.bcris.site',
    'http://bcris.site',
    'http://www.bcris.site',
]

# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold'u en üste ekle
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rcb_predictor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rcb_predictor.middleware.SitePasswordMiddleware',  # Site giriş şifresi
]

ROOT_URLCONF = 'bcris_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bcris_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # /app/staticfiles
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # /app/media


# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "BCRIS Admin Panel",
    "SITE_HEADER": "BCRIS - Breast Cancer Response Intelligence System",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/logo.png",
        "dark": lambda request: "/static/logo.png",
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/logo.png",
        "dark": lambda request: "/static/logo.png",
    },
    "SITE_SYMBOL": "🧬",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/logo.png",
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "bcris_project.settings.environment_callback",
    "DASHBOARD_CALLBACK": "bcris_project.settings.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",   # Çok açık mavi
            "100": "219 234 254",  # Açık mavi
            "200": "191 219 254",  # Açık mavi
            "300": "147 197 253",  # Orta açık mavi
            "400": "96 165 250",   # Orta mavi
            "500": "59 130 246",   # Ana mavi (tıbbi mavi)
            "600": "37 99 235",    # Koyu mavi
            "700": "29 78 216",    # Daha koyu mavi
            "800": "30 64 175",    # Çok koyu mavi
            "900": "30 58 138",    # En koyu mavi
            "950": "23 37 84",     # Neredeyse siyah mavi
        },
    },
    "STYLES": [
        lambda request: "/static/admin_custom.css",
    ],
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "tr": "🇹🇷",
                "en": "🇬🇧",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Ana Sayfa",
                "separator": True,
                "items": [
                    {
                        "title": "BCRIS Ana Sayfa",
                        "icon": "home",
                        "link": lambda request: "/",
                    },
                    {
                        "title": "Teşekkür Sayfası",
                        "icon": "favorite",
                        "link": lambda request: "/thanks/",
                    },
                ],
            },
            {
                "title": "Özellikler",
                "separator": True,
                "items": [
                    {
                        "title": "Özellik Grupları",
                        "icon": "folder",
                        "link": lambda request: "/admin/rcb_predictor/featuregroup/",
                    },
                    {
                        "title": "Özellikler",
                        "icon": "list",
                        "link": lambda request: "/admin/rcb_predictor/feature/",
                    },
                    {
                        "title": "Kategori Seçenekleri",
                        "icon": "check_box",
                        "link": lambda request: "/admin/rcb_predictor/categoryoption/",
                    },
                    {
                        "title": "Değişken Bilgileri",
                        "icon": "info",
                        "link": lambda request: "/admin/rcb_predictor/variableinfo/",
                    },
                ],
            },
            {
                "title": "Tedavi",
                "separator": True,
                "items": [
                    {
                        "title": "Tedavi Mesajları",
                        "icon": "medical_services",
                        "link": lambda request: "/admin/rcb_predictor/treatmentmessage/",
                    },
                ],
            },
            {
                "title": "Model",
                "separator": True,
                "items": [
                    {
                        "title": "ML Modeller",
                        "icon": "psychology",
                        "link": lambda request: "/admin/rcb_predictor/mlmodel/",
                    },
                ],
            },
            {
                "title": "Hekimler ve Veri",
                "separator": True,
                "items": [
                    {
                        "title": "Hekimler",
                        "icon": "person",
                        "link": lambda request: "/admin/rcb_predictor/physician/",
                    },
                    {
                        "title": "Hasta Verileri",
                        "icon": "upload_file",
                        "link": lambda request: "/admin/rcb_predictor/patientdataupload/",
                    },
                    {
                        "title": "ML Eğitim Logları",
                        "icon": "analytics",
                        "link": lambda request: "/admin/rcb_predictor/mltraininglog/",
                    },
                ],
            },
            {
                "title": "Dosyalar",
                "separator": True,
                "items": [
                    {
                        "title": "İndirilebilir Dosyalar",
                        "icon": "download",
                        "link": lambda request: "/admin/rcb_predictor/downloadablefile/",
                    },
                ],
            },
            {
                "title": "Sistem",
                "separator": True,
                "items": [
                    {
                        "title": "Sistem Ayarları",
                        "icon": "settings",
                        "link": lambda request: "/admin/rcb_predictor/systemsettings/",
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """Admin panelde environment badge göster"""
    return ["Development", "warning"]


def dashboard_callback(request, context):
    """Admin dashboard için özel içerik"""
    from rcb_predictor.models import Feature, TreatmentMessage, MLModel, Physician, PatientDataUpload
    
    context.update({
        "navigation": [
            {
                "title": "Sistem İstatistikleri",
                "items": [
                    {
                        "title": "Toplam Özellik",
                        "value": Feature.objects.count(),
                        "icon": "list",
                    },
                    {
                        "title": "Aktif Özellik",
                        "value": Feature.objects.filter(is_active=True).count(),
                        "icon": "check_circle",
                    },
                    {
                        "title": "Tedavi Mesajı",
                        "value": TreatmentMessage.objects.filter(is_active=True).count(),
                        "icon": "medical_services",
                    },
                    {
                        "title": "Aktif Model",
                        "value": MLModel.objects.filter(is_active=True).count(),
                        "icon": "psychology",
                    },
                ],
            },
            {
                "title": "Hekim ve Veri İstatistikleri",
                "items": [
                    {
                        "title": "Onaylı Hekim",
                        "value": Physician.objects.filter(approval_status='approved').count(),
                        "icon": "person",
                    },
                    {
                        "title": "Onay Bekleyen",
                        "value": Physician.objects.filter(approval_status='pending').count(),
                        "icon": "pending",
                    },
                    {
                        "title": "Yüklenen Veri",
                        "value": PatientDataUpload.objects.count(),
                        "icon": "upload_file",
                    },
                    {
                        "title": "İşlem Bekleyen",
                        "value": PatientDataUpload.objects.filter(processing_status='pending').count(),
                        "icon": "hourglass_empty",
                    },
                ],
            },
        ],
    })
    return context

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/physician/dashboard/'
LOGOUT_REDIRECT_URL = '/'
