# Generated by Django 5.2.7 on 2025-12-04 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod (i1, i2, ...)')),
                ('name_tr', models.CharField(max_length=200, verbose_name='Özellik Adı (TR)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Özellik Adı (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=100, verbose_name='Grup Adı (TR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Grup Adı (EN)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Özellik Grubu',
                'verbose_name_plural': 'Özellik Grupları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('model_file', models.FileField(upload_to='ml_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['joblib', 'pkl'])], verbose_name='Model Dosyası (.joblib)')),
                ('feature_list_json', models.TextField(help_text='Özellik listesi', verbose_name='Feature List (JSON)')),
                ('class_order_json', models.TextField(help_text='Sınıf sırası [0, 1, 2, 3]', verbose_name='Class Order (JSON)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif Model')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Modeller',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Anahtar')),
                ('value', models.TextField(verbose_name='Değer')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
            },
        ),
        migrations.CreateModel(
            name='TreatmentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True, verbose_name='Mesaj ID')),
                ('title_tr', models.CharField(max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Başlık (EN)')),
                ('message_tr', models.TextField(verbose_name='Mesaj (TR)')),
                ('message_en', models.TextField(blank=True, verbose_name='Mesaj (EN)')),
                ('message_type', models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyarı'), ('critical', 'Kritik')], default='info', max_length=20, verbose_name='Mesaj Tipi')),
                ('priority', models.IntegerField(default=0, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('conditions_json', models.TextField(help_text='Örnek: {"i2": 1, "i3": [1, 2]}', verbose_name='Koşullar (JSON)')),
            ],
            options={
                'verbose_name': 'Tedavi Mesajı',
                'verbose_name_plural': 'Tedavi Mesajları',
                'ordering': ['-priority', 'message_id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_tr', models.CharField(max_length=200, verbose_name='Etiket (TR)')),
                ('label_en', models.CharField(blank=True, max_length=200, verbose_name='Etiket (EN)')),
                ('value', models.IntegerField(verbose_name='Değer')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='rcb_predictor.feature', verbose_name='Özellik')),
            ],
            options={
                'verbose_name': 'Kategori Seçeneği',
                'verbose_name_plural': 'Kategori Seçenekleri',
                'ordering': ['feature', 'order'],
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rcb_predictor.featuregroup', verbose_name='Grup'),
        ),
        migrations.CreateModel(
            name='VariableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tr', models.TextField(verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (EN)')),
                ('how_measured_tr', models.TextField(verbose_name='Nasıl Ölçülür (TR)')),
                ('how_measured_en', models.TextField(blank=True, verbose_name='Nasıl Ölçülür (EN)')),
                ('clinical_significance_tr', models.TextField(verbose_name='Klinik Önemi (TR)')),
                ('clinical_significance_en', models.TextField(blank=True, verbose_name='Klinik Önemi (EN)')),
                ('how_to_find_tr', models.TextField(verbose_name='Nasıl Bulunur (TR)')),
                ('how_to_find_en', models.TextField(blank=True, verbose_name='Nasıl Bulunur (EN)')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='rcb_predictor.feature', verbose_name='Özellik')),
            ],
            options={
                'verbose_name': 'Değişken Bilgisi',
                'verbose_name_plural': 'Değişken Bilgileri',
            },
        ),
    ]
