# Generated by Django 5.2.7 on 2025-12-04 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcb_predictor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='patient_data/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])], verbose_name='Excel Dosyası')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('file_size', models.IntegerField(null=True, verbose_name='Dosya Boyutu (bytes)')),
                ('patient_count', models.IntegerField(default=0, verbose_name='Hasta Sayısı')),
                ('description', models.TextField(blank=True, help_text='Veri seti hakkında notlar', verbose_name='Açıklama')),
                ('processing_status', models.CharField(choices=[('pending', 'İşlem Bekliyor'), ('reviewing', 'İnceleniyor'), ('processed', 'İşlendi'), ('rejected', 'Reddedildi'), ('integrated', "ML'e Entegre Edildi")], default='pending', max_length=20, verbose_name='İşlem Durumu')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('processed_data_json', models.TextField(blank=True, help_text='ML formatına çevrilmiş veri', verbose_name='İşlenmiş Veri (JSON)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_uploads', to=settings.AUTH_USER_MODEL, verbose_name='İşleyen')),
            ],
            options={
                'verbose_name': 'Hasta Verisi',
                'verbose_name_plural': 'Hasta Verileri',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MLTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateTimeField(auto_now_add=True, verbose_name='Eğitim Tarihi')),
                ('total_patients', models.IntegerField(verbose_name='Toplam Hasta Sayısı')),
                ('training_patients', models.IntegerField(verbose_name='Eğitim Hasta Sayısı')),
                ('test_patients', models.IntegerField(verbose_name='Test Hasta Sayısı')),
                ('accuracy', models.FloatField(verbose_name='Doğruluk (%)')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('metrics_json', models.TextField(blank=True, verbose_name='Detaylı Metrikler (JSON)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='rcb_predictor.mlmodel', verbose_name='Model')),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Eğiten')),
                ('data_sources', models.ManyToManyField(blank=True, related_name='training_logs', to='rcb_predictor.patientdataupload', verbose_name='Kullanılan Veri Setleri')),
            ],
            options={
                'verbose_name': 'ML Eğitim Logu',
                'verbose_name_plural': 'ML Eğitim Logları',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('institution', models.CharField(max_length=200, verbose_name='Kurum/Hastane')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Bölüm')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ünvan')),
                ('id_card_image', models.ImageField(help_text='Sağlık Bakanlığı onaylı kimlik kartı - TC kimlik numarası kapatılmalı (KVKK)', upload_to='physician_ids/', verbose_name='Kimlik Kartı (TC Kapalı)')),
                ('approval_status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Onay Durumu')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_physicians', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hekim',
                'verbose_name_plural': 'Hekimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patientdataupload',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='rcb_predictor.physician', verbose_name='Hekim'),
        ),
    ]
