# Generated by Django 5.2.7 on 2025-12-04 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcb_predictor', '0002_patientdataupload_mltraininglog_physician_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('sample_excel', 'Örnek Excel Dosyası'), ('variable_format', 'Değişken Formatı Bilgi Dosyası')], max_length=50, unique=True, verbose_name='Dosya Tipi')),
                ('file', models.FileField(upload_to='downloadable_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'pdf', 'docx', 'doc', 'txt'])], verbose_name='Dosya')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama (TR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama (EN)')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Yüklenme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'İndirilebilir Dosya',
                'verbose_name_plural': 'İndirilebilir Dosyalar',
                'ordering': ['file_type'],
            },
        ),
    ]
