# Generated by Django 5.2.7 on 2025-12-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcb_predictor', '0005_downloadablefile_version_alter_downloadablefile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanksPageContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('title', models.CharField(blank=True, help_text='Örn: Prof. Dr., Doç. Dr., Uzm. Dr.', max_length=100, verbose_name='Ünvan')),
                ('institution', models.CharField(max_length=200, verbose_name='Kurum/Hastane')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Bölüm')),
                ('contribution_type', models.CharField(blank=True, help_text='Örn: Veri Katkısı, Danışmanlık', max_length=100, verbose_name='Katkı Türü')),
                ('data_count', models.IntegerField(default=0, verbose_name='Veri Seti Sayısı')),
                ('patient_count', models.IntegerField(default=0, verbose_name='Hasta Sayısı')),
                ('order', models.IntegerField(default=0, help_text='Küçük sayılar önce gösterilir', verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Teşekkür Sayfası Katkıcısı',
                'verbose_name_plural': 'Teşekkür Sayfası Katkıcıları',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ThanksPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(default='🙏 Teşekkürler', max_length=200, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(default='🙏 Thanks', max_length=200, verbose_name='Başlık (EN)')),
                ('subtitle_tr', models.TextField(default='BCRIS projesine veri katkısında bulunan değerli hekimlerimize ve kurumlarına en içten teşekkürlerimizi sunarız.', verbose_name='Alt Başlık (TR)')),
                ('subtitle_en', models.TextField(default='We extend our sincere thanks to our valued physicians and institutions who contributed data to the BCRIS project.', verbose_name='Alt Başlık (EN)')),
                ('intro_title_tr', models.CharField(default='Projeye Katkılarınız', max_length=200, verbose_name='Giriş Başlığı (TR)')),
                ('intro_title_en', models.CharField(default='Your Contributions', max_length=200, verbose_name='Giriş Başlığı (EN)')),
                ('intro_text_tr', models.TextField(default='Paylaştığınız hasta verileri sayesinde makine öğrenmesi modelimiz sürekli gelişiyor ve daha doğru tahminler yapabiliyor.', verbose_name='Giriş Metni (TR)')),
                ('intro_text_en', models.TextField(default='Thanks to the patient data you share, our machine learning model continues to improve and make more accurate predictions.', verbose_name='Giriş Metni (EN)')),
                ('show_stats', models.BooleanField(default=True, verbose_name='İstatistikleri Göster')),
                ('total_patients_override', models.IntegerField(blank=True, help_text='Boş bırakılırsa otomatik hesaplanır', null=True, verbose_name='Toplam Hasta (Manuel)')),
                ('model_accuracy_override', models.FloatField(blank=True, help_text='Boş bırakılırsa son eğitimden alınır', null=True, verbose_name='Model Doğruluğu (Manuel %)')),
            ],
            options={
                'verbose_name': 'Teşekkür Sayfası Ayarı',
                'verbose_name_plural': 'Teşekkür Sayfası Ayarları',
            },
        ),
    ]
